const express=require('express');
const {get,all,run,logAudit}=require('../db');
const {requireAuth}=require('../middleware/auth');
const {requirePermission}=require('../authz');
const asyncHandler=require('../middleware/asyncHandler');
const svc=require('../curriculum');
const router=express.Router();
const view=requirePermission('curriculum.View');
const create=requirePermission('curriculum.Create');
const update=requirePermission('curriculum.Update');
const action=(fn)=>asyncHandler(async(req,res)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({error:e.message,code:e.code});throw e;}});

router.get('/',requireAuth,view,action(async(req,res)=>res.json(await svc.listCurricula(req.query.programId))));
router.post('/',requireAuth,create,action(async(req,res)=>res.status(201).json(await svc.createCurriculum(req.body,req.user))));
router.get('/unassigned-students',requireAuth,requirePermission('curriculum.AssignStudent'),action(async(req,res)=>res.json(await all(`SELECT u.id,u.name,u.email,sp.programId,p.name programName FROM users u LEFT JOIN student_profiles sp ON sp.studentId=u.id LEFT JOIN programs p ON p.id=sp.programId LEFT JOIN student_curriculum sc ON sc.studentId=u.id AND LOWER(sc.status)='active' WHERE u.role='student' AND sc.id IS NULL ORDER BY u.name`))));
router.get('/students/:studentId/assignment',requireAuth,view,action(async(req,res)=>res.json(await svc.getStudentAssignment(req.params.studentId))));
router.put('/students/:studentId/assignment',requireAuth,requirePermission('curriculum.AssignStudent'),action(async(req,res)=>res.json(await svc.assignStudent(req.params.studentId,req.body.curriculumId,req.body,req.user))));
router.get('/students/:studentId/audit',requireAuth,requirePermission('curriculum.AuditStudent'),action(async(req,res)=>res.json(await svc.studentAudit(req.params.studentId))));
router.get('/:id',requireAuth,view,action(async(req,res)=>{const x=await svc.getCurriculumStructure(req.params.id);if(!x)return res.status(404).json({error:'Curriculum not found.'});res.json(x);}));
router.put('/:id',requireAuth,update,action(async(req,res)=>res.json(await svc.updateCurriculum(req.params.id,req.body,req.user))));
router.post('/:id/validate',requireAuth,view,action(async(req,res)=>res.json(await svc.validateCurriculum(req.params.id))));
router.post('/:id/activate',requireAuth,requirePermission('curriculum.Activate'),action(async(req,res)=>res.json(await svc.activateCurriculum(req.params.id,req.user))));
router.post('/:id/archive',requireAuth,requirePermission('curriculum.Archive'),action(async(req,res)=>{await svc.archiveCurriculum(req.params.id,req.user);res.json({ok:true});}));
router.post('/:id/clone',requireAuth,create,action(async(req,res)=>res.status(201).json(await svc.cloneCurriculum(req.params.id,req.body,req.user))));
router.get('/:id/students',requireAuth,view,action(async(req,res)=>res.json(await all(`SELECT u.id,u.name,u.email,sc.assignedAt,sc.notes FROM student_curriculum sc JOIN users u ON u.id=sc.studentId WHERE sc.curriculumId=? AND LOWER(sc.status)='active' ORDER BY u.name`,[req.params.id]))));
router.get('/:id/compare/:otherId',requireAuth,requirePermission('curriculum.Compare'),action(async(req,res)=>{const [a,b]=await Promise.all([svc.getCurriculumStructure(req.params.id),svc.getCurriculumStructure(req.params.otherId)]);if(!a||!b)return res.status(404).json({error:'Curriculum not found.'});const flatten=x=>new Map(x.semesters.flatMap(s=>s.courses.map(c=>[c.name.trim().toLowerCase(),{...c,semesterNumber:s.semesterNumber}])));const am=flatten(a),bm=flatten(b);res.json({left:a.curriculum,right:b.curriculum,added:[...bm].filter(([k])=>!am.has(k)).map(([,v])=>v),removed:[...am].filter(([k])=>!bm.has(k)).map(([,v])=>v),changed:[...am].filter(([k,v])=>bm.has(k)&&(bm.get(k).semesterNumber!==v.semesterNumber||bm.get(k).courseType!==v.courseType)).map(([k,v])=>({before:v,after:bm.get(k)}))});}));

router.post('/:id/semesters',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const d=req.body;if(!Number.isInteger(Number(d.semesterNumber))||Number(d.semesterNumber)<1)return res.status(400).json({error:'semesterNumber must be a positive whole number.'});try{const x=await run(`INSERT INTO curriculum_semester(curriculumId,semesterNumber,name,minimumCredits,maximumCredits,createdAt,updatedAt) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[req.params.id,d.semesterNumber,d.name||null,d.minimumCredits??null,d.maximumCredits??null]);await logAudit(req.user,'curriculum-semester-add','curriculum_semester',x.id,{curriculumId:Number(req.params.id),...d});res.status(201).json(await get('SELECT * FROM curriculum_semester WHERE id=?',[x.id]));}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'This curriculum already has that semester number.'});throw e;}}));
router.put('/:id/semesters/:semesterId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const old=await get('SELECT * FROM curriculum_semester WHERE id=? AND curriculumId=?',[req.params.semesterId,req.params.id]);if(!old)return res.status(404).json({error:'Curriculum semester not found.'});const d=req.body;await run(`UPDATE curriculum_semester SET semesterNumber=?,name=?,minimumCredits=?,maximumCredits=?,updatedAt=CURRENT_TIMESTAMP WHERE id=?`,[d.semesterNumber??old.semesterNumber,d.name??old.name,d.minimumCredits===undefined?old.minimumCredits:d.minimumCredits,d.maximumCredits===undefined?old.maximumCredits:d.maximumCredits,old.id]);const row=await get('SELECT * FROM curriculum_semester WHERE id=?',[old.id]);await logAudit(req.user,'curriculum-semester-update','curriculum_semester',old.id,null,old,row);res.json(row);}));
router.delete('/:id/semesters/:semesterId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const used=await get('SELECT id FROM curriculum_course WHERE curriculumSemesterId=? LIMIT 1',[req.params.semesterId]);if(used)return res.status(409).json({error:'Remove the semester courses first.'});await run('DELETE FROM curriculum_semester WHERE id=? AND curriculumId=?',[req.params.semesterId,req.params.id]);await logAudit(req.user,'curriculum-semester-remove','curriculum_semester',req.params.semesterId,{curriculumId:Number(req.params.id)});res.json({ok:true});}));
router.post('/:id/courses',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const d=req.body;const sem=await get('SELECT * FROM curriculum_semester WHERE id=? AND curriculumId=?',[d.curriculumSemesterId,req.params.id]);if(!sem)return res.status(400).json({error:'Semester does not belong to this curriculum.'});const type=d.courseType||'required';if(!['required','elective'].includes(type))return res.status(400).json({error:"courseType must be 'required' or 'elective'."});if(type==='required'&&d.electiveGroupId)return res.status(400).json({error:'A required course cannot use an elective group.'});if(d.electiveGroupId&&!await get('SELECT id FROM elective_group WHERE id=? AND curriculumId=?',[d.electiveGroupId,req.params.id]))return res.status(400).json({error:'Elective group does not belong to this curriculum.'});try{const x=await run(`INSERT INTO curriculum_course(curriculumSemesterId,courseId,required,electiveGroupId,minimumGrade,sequence,notes,courseType,minimumPassingGrade,recommendedSequence,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[sem.id,d.courseId,type==='required'?1:0,d.electiveGroupId||null,d.minimumPassingGrade||null,d.recommendedSequence??0,d.notes||null,type,d.minimumPassingGrade||null,d.recommendedSequence??0]);await logAudit(req.user,'curriculum-course-add','curriculum_course',x.id,{curriculumId:Number(req.params.id),...d});res.status(201).json(await get('SELECT * FROM curriculum_course WHERE id=?',[x.id]));}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'This course is already assigned to that curriculum semester.'});throw e;}}));
router.put('/:id/courses/:courseAssignmentId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const old=await get(`SELECT cc.* FROM curriculum_course cc JOIN curriculum_semester cs ON cs.id=cc.curriculumSemesterId WHERE cc.id=? AND cs.curriculumId=?`,[req.params.courseAssignmentId,req.params.id]);if(!old)return res.status(404).json({error:'Curriculum course not found.'});const d=req.body,type=d.courseType||old.courseType||(old.required?'required':'elective');if(type==='required'&&d.electiveGroupId)return res.status(400).json({error:'A required course cannot use an elective group.'});await run(`UPDATE curriculum_course SET courseType=?,required=?,electiveGroupId=?,minimumPassingGrade=?,minimumGrade=?,recommendedSequence=?,sequence=?,notes=?,updatedAt=CURRENT_TIMESTAMP WHERE id=?`,[type,type==='required'?1:0,type==='required'?null:(d.electiveGroupId??old.electiveGroupId),d.minimumPassingGrade??old.minimumPassingGrade??old.minimumGrade,d.minimumPassingGrade??old.minimumPassingGrade??old.minimumGrade,d.recommendedSequence??old.recommendedSequence??old.sequence,d.recommendedSequence??old.recommendedSequence??old.sequence,d.notes===undefined?old.notes:d.notes,old.id]);const row=await get('SELECT * FROM curriculum_course WHERE id=?',[old.id]);await logAudit(req.user,'curriculum-course-update','curriculum_course',old.id,null,old,row);res.json(row);}));
router.delete('/:id/courses/:courseAssignmentId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const old=await get(`SELECT cc.* FROM curriculum_course cc JOIN curriculum_semester cs ON cs.id=cc.curriculumSemesterId WHERE cc.id=? AND cs.curriculumId=?`,[req.params.courseAssignmentId,req.params.id]);if(!old)return res.status(404).json({error:'Curriculum course not found.'});await run('DELETE FROM curriculum_course WHERE id=?',[old.id]);await logAudit(req.user,'curriculum-course-remove','curriculum_course',old.id,null,old,null);res.json({ok:true});}));
router.post('/:id/elective-groups',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const d=req.body;if(!String(d.name||'').trim())return res.status(400).json({error:'Name is required.'});const x=await run(`INSERT INTO elective_group(curriculumId,name,requiredCount,requiredCredits,minimumCourses,minimumCredits,maximumCourses,description,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[req.params.id,d.name.trim(),d.minimumCourses??0,d.minimumCredits??0,d.minimumCourses??0,d.minimumCredits??0,d.maximumCourses??null,d.description||null]);await logAudit(req.user,'elective-group-create','elective_group',x.id,{curriculumId:Number(req.params.id),...d});res.status(201).json(await get('SELECT * FROM elective_group WHERE id=?',[x.id]));}));
router.put('/:id/elective-groups/:groupId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);const old=await get('SELECT * FROM elective_group WHERE id=? AND curriculumId=?',[req.params.groupId,req.params.id]);if(!old)return res.status(404).json({error:'Elective group not found.'});const d=req.body;await run(`UPDATE elective_group SET name=?,minimumCourses=?,requiredCount=?,minimumCredits=?,requiredCredits=?,maximumCourses=?,description=?,updatedAt=CURRENT_TIMESTAMP WHERE id=?`,[d.name??old.name,d.minimumCourses??old.minimumCourses??old.requiredCount,d.minimumCourses??old.minimumCourses??old.requiredCount,d.minimumCredits??old.minimumCredits??old.requiredCredits,d.minimumCredits??old.minimumCredits??old.requiredCredits,d.maximumCourses===undefined?old.maximumCourses:d.maximumCourses,d.description===undefined?old.description:d.description,old.id]);const row=await get('SELECT * FROM elective_group WHERE id=?',[old.id]);await logAudit(req.user,'elective-group-update','elective_group',old.id,null,old,row);res.json(row);}));
router.delete('/:id/elective-groups/:groupId',requireAuth,update,action(async(req,res)=>{await svc.assertDraft(req.params.id);if(await get('SELECT id FROM curriculum_course WHERE electiveGroupId=? LIMIT 1',[req.params.groupId]))return res.status(409).json({error:'Remove this group from curriculum courses first.'});const old=await get('SELECT * FROM elective_group WHERE id=? AND curriculumId=?',[req.params.groupId,req.params.id]);if(!old)return res.status(404).json({error:'Elective group not found.'});await run('DELETE FROM elective_group WHERE id=?',[old.id]);await logAudit(req.user,'elective-group-delete','elective_group',old.id,null,old,null);res.json({ok:true});}));

module.exports=router;
