import { useEffect, useState } from 'react';
import Section from '../components/Section.jsx';
import { useNavigation } from '../context/NavigationContext.jsx';
import { useToast } from '../context/ToastContext.jsx';
import { downloadGraduatesRegistry, fetchGraduateDetail, fetchGraduatesRegistry, updateGraduationIssuance } from '../api.js';

export default function GraduatesRegistryPage(){
  const {activeSection,sectionFocus,showSection}=useNavigation(),{toast}=useToast();
  const [data,setData]=useState({items:[],total:0,page:1,pageSize:25}),[filters,setFilters]=useState({search:'',year:'',recordStatus:'',page:1,pageSize:25}),[loading,setLoading]=useState(false),[detail,setDetail]=useState(null);
  const load=async()=>{setLoading(true);try{setData(await fetchGraduatesRegistry(filters));}catch(e){toast(e.message,'error');}finally{setLoading(false);}};
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(activeSection==='graduates-registry')load();},[activeSection,filters.year,filters.recordStatus,filters.page]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(activeSection==='graduates-registry'&&sectionFocus?.graduateId)open(sectionFocus.graduateId);},[activeSection,sectionFocus?.graduateId]);
  const search=e=>{e.preventDefault();setFilters(f=>({...f,page:1}));load();};
  const open=async id=>{try{setDetail(await fetchGraduateDetail(id));}catch(e){toast(e.message,'error');}};
  const issuance=async(type,status)=>{try{setDetail(await updateGraduationIssuance(detail.id,type,{status}));await load();toast(`${type} status updated.`);}catch(e){toast(e.message,'error');}};
  return <Section name="graduates-registry"><div className="topbar"><i className="ti ti-certificate" aria-hidden="true"></i><h2>Graduates Registry</h2><div className="topbar-actions"><button className="btn-sm" onClick={()=>downloadGraduatesRegistry(filters)}><i className="ti ti-file-spreadsheet"></i> Export official register</button></div></div><div id="content">
    <p className="field-hint">This registry lists formally finalized degree awards only. Finalized records are immutable except through authorized correction or revocation workflows.</p>
    <form className="panel" style={{padding:14,marginBottom:16}} onSubmit={search}><div className="form-row-3"><label className="form-row"><span className="form-label">Search</span><input value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value}))} placeholder="Graduate, student number, or name"/></label><label className="form-row"><span className="form-label">Graduation year</span><input value={filters.year} onChange={e=>setFilters(f=>({...f,year:e.target.value}))} placeholder="2026"/></label><label className="form-row"><span className="form-label">Record status</span><select value={filters.recordStatus} onChange={e=>setFilters(f=>({...f,recordStatus:e.target.value,page:1}))}><option value="">All</option><option value="active">Active</option><option value="corrected">Corrected</option><option value="revoked">Revoked</option></select></label></div><button className="btn-sm" type="submit"><i className="ti ti-search"></i> Search</button></form>
    {detail&&<div className="panel" style={{padding:16,marginBottom:16}}><div className="panel-header"><div><div className="panel-title">{detail.name} · {detail.graduateNumber}</div><div className="field-hint">{detail.degreeAwarded} · {detail.programName} · finalized {detail.finalizedAt}</div></div><button className="icon-btn" onClick={()=>setDetail(null)}><i className="ti ti-x"></i></button></div><div className="form-row-3"><div><div className="form-label">Academic snapshot</div><div>GPA {detail.finalGpa??'—'} · {detail.totalCreditsCompleted??'—'} credits</div><div>{detail.curriculumVersion||'No curriculum snapshot'}</div></div><label><span className="form-label">Certificate</span><select value={detail.certificateStatus||'not_generated'} onChange={e=>issuance('certificate',e.target.value)}><option>not_generated</option><option>generated</option><option>printed</option><option>issued</option><option>collected</option><option>withheld</option><option>revoked</option></select><div className="field-hint">{detail.certificateNumber}</div></label><label><span className="form-label">Transcript</span><select value={detail.transcriptStatus||'pending'} onChange={e=>issuance('transcript',e.target.value)}><option>pending</option><option>ready</option><option>issued</option><option>collected</option><option>withheld</option></select></label></div><div style={{display:'flex',gap:8,marginTop:12}}><button className="btn-sm" onClick={()=>showSection('student-detail',{studentId:detail.studentId})}>Student history</button><button className="btn-sm" onClick={()=>showSection('transcript',{studentId:detail.studentId})}>Final transcript</button></div>{detail.audits?.[0]&&<details style={{marginTop:12}}><summary>Final graduation audit ({detail.audits[0].result})</summary><ul>{detail.audits[0].snapshot.reasons?.map((r,i)=><li key={i}>{r.message}</li>)||<li>All requirements passed.</li>}</ul></details>}{detail.approval?.history?.length>0&&<details><summary>Approval history</summary><ol>{detail.approval.history.map(h=><li key={h.id}>{h.label}: {h.decision} by {h.reviewerName}</li>)}</ol></details>}</div>}
    <div className="panel" style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Graduate number</th><th>Student</th><th>Program / degree</th><th>Department / college</th><th>Graduation</th><th>GPA / credits</th><th>Certificate</th><th>Transcript</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="field-hint">Loading official registry…</td></tr>:data.items.length===0?<tr><td colSpan="9" className="field-hint">No finalized graduates match these filters.</td></tr>:data.items.map(r=><tr key={r.id} onClick={()=>open(r.id)} style={{cursor:'pointer'}}><td><strong>{r.graduateNumber}</strong></td><td>{r.name}<div className="field-hint">{r.idNumber}</div></td><td>{r.programName}<div className="field-hint">{r.degreeAwarded}</div></td><td>{r.departmentName||'—'}<div className="field-hint">{r.collegeName||'—'}</div></td><td>{r.officialGraduationDate}<div className="field-hint">{r.graduationTerm||'—'}</div></td><td>{r.finalGpa??'—'} · {r.totalCreditsCompleted??'—'}</td><td>{r.certificateStatus}<div className="field-hint">{r.certificateNumber}</div></td><td>{r.transcriptStatus}</td><td><span className={`pill ${r.recordStatus==='revoked'?'pill-red':r.recordStatus==='corrected'?'pill-amber':'pill-green'}`}>{r.recordStatus}</span></td></tr>)}</tbody></table></div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12}}><span className="field-hint">{data.total} official records</span><div><button className="btn-sm" disabled={filters.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}>Previous</button> <button className="btn-sm" disabled={data.page*data.pageSize>=data.total} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}>Next</button></div></div>
  </div></Section>;
}
