process.env.DB_PATH=':memory:';
process.env.JWT_SECRET='notification-lifecycle-test-secret';
const test=require('node:test');
const assert=require('node:assert/strict');
const jwt=require('jsonwebtoken');
const db=require('../db');
const {JWT_SECRET}=require('../middleware/auth');
const {createNotification,safeCreateNotification}=require('../notificationTypes');

test('notification service validation, isolation, deduplication and preferences',async()=>{
  await db.init();
  const u=await db.run(`INSERT INTO users(name,email,role) VALUES('Preference User','pref@test.invalid','student')`);
  await assert.rejects(()=>createNotification({recipientUserId:999999,type:'payment_recorded',message:'x'}),/does not exist/);
  await assert.rejects(()=>createNotification({recipientUserId:u.id,type:'not_real',message:'x'}),/allowlist/);
  const first=await createNotification({recipientUserId:u.id,type:'payment_recorded',message:'Payment recorded',deduplicationKey:'unit:dedup'});
  const duplicate=await createNotification({recipientUserId:u.id,type:'payment_recorded',message:'Payment recorded',deduplicationKey:'unit:dedup'});
  assert.equal(duplicate.id,first.id);assert.equal(duplicate.duplicate,true);
  await db.run(`INSERT INTO notification_preferences(userId,category,enabled) VALUES(?,'lms',0)`,[u.id]);
  assert.equal((await createNotification({recipientUserId:u.id,type:'assignment_posted',message:'Optional',category:'lms'})).skipped,true);
  const mandatory=await createNotification({recipientUserId:u.id,type:'password_changed',message:'Mandatory',category:'lms'});
  assert.equal(mandatory.type,'password_changed');
  const safe=await safeCreateNotification({recipientUserId:999999,type:'payment_recorded',message:'workflow survives'});
  assert.equal(safe.failed,true);assert.equal((await db.get('SELECT COUNT(*) n FROM notification_delivery_failures')).n,1);
});

test('real academic lifecycle endpoints generate actionable notifications',async t=>{
  const express=require('express'),app=express();app.use(express.json());
  require('../appealsFlow');
  app.use('/api/enrollments',require('../routes/enrollments'));app.use('/api/attendance',require('../routes/attendance'));
  app.use('/api/exams',require('../routes/exams'));app.use('/api/grades',require('../routes/grades'));
  app.use('/api/progression',require('../routes/progression'));app.use('/api/finance',require('../routes/finance'));
  app.use('/api/approvals',require('../routes/approvals'));app.use('/api/graduation',require('../routes/graduation'));
  app.use('/api/notifications',require('../routes/notifications'));
  const admin=await db.run(`INSERT INTO users(name,email,role) VALUES('Lifecycle Admin','lifecycle-admin@test.invalid','admin')`);
  const departmentReviewer=await db.run(`INSERT INTO users(name,email,role) VALUES('Department Reviewer','department-reviewer@test.invalid','dept_head')`);
  const student=await db.run(`INSERT INTO users(name,email,role,idNumber) VALUES('Lifecycle Student','lifecycle-student@test.invalid','student','STU-NOTIFY-1')`);
  const seatHolder=await db.run(`INSERT INTO users(name,email,role,idNumber) VALUES('Seat Holder','seat-holder@test.invalid','student','STU-WAIT-1')`);
  const waitlistedStudent=await db.run(`INSERT INTO users(name,email,role,idNumber) VALUES('Waitlisted Student','waitlisted@test.invalid','student','STU-WAIT-2')`);
  await db.run(`INSERT INTO user_roles(userId,role) VALUES(?,'registrar')`,[admin.id]);
  const dept=await db.run(`INSERT INTO departments(name) VALUES('Notification Studies')`);
  await db.run('UPDATE users SET departmentId = ? WHERE id = ?', [dept.id, departmentReviewer.id]);
  const program=await db.run(`INSERT INTO programs(name,departmentId,degreeLevel,totalCredits) VALUES('Lifecycle Program',?,'BSc',6)`,[dept.id]);
  const term=await db.run(`INSERT INTO terms(name,startDate,endDate,isActive) VALUES('Lifecycle 2026','2026-01-01','2026-12-31',1)`);
  const nextTerm=await db.run(`INSERT INTO terms(name,startDate,endDate,isActive) VALUES('Lifecycle 2027','2027-01-01','2027-12-31',0)`);
  const room=await db.run(`INSERT INTO rooms(name,type,capacity) VALUES('N-101','Lecture',50)`);
  const course=await db.run(`INSERT INTO courses(code,name,departmentId,credits,roomId,maxStudents,termId,programId) VALUES('NTF101','Notification Lifecycle',?,3,?,30,?,?)`,[dept.id,room.id,term.id,program.id]);
  const secondCourse=await db.run(`INSERT INTO courses(code,name,departmentId,credits,roomId,maxStudents,termId,programId) VALUES('NTF201','Advanced Notification Lifecycle',?,3,?,30,?,?)`,[dept.id,room.id,nextTerm.id,program.id]);
  const waitlistCourse=await db.run(`INSERT INTO courses(code,name,departmentId,credits,roomId,maxStudents,termId,programId) VALUES('NTF-WAIT','Waitlist Lifecycle',?,1,?,1,?,?)`,[dept.id,room.id,nextTerm.id,program.id]);
  await db.run(`INSERT INTO student_profiles(studentId,departmentId,programId,programSemester,studentStatus,enrollmentDate,semesterStatus) VALUES(?,?,?,1,'Active','2026-01-01','In Progress')`,[student.id,dept.id,program.id]);
  for(const id of [seatHolder.id,waitlistedStudent.id])await db.run(`INSERT INTO student_profiles(studentId,departmentId,programId,programSemester,studentStatus,enrollmentDate,semesterStatus) VALUES(?,?,?,1,'Active','2026-01-01','In Progress')`,[id,dept.id,program.id]);
  const curriculum=await db.run(`INSERT INTO curriculum(programId,curriculumName,status,totalCredits,totalRequiredCredits,catalogYear) VALUES(?,'Lifecycle Curriculum','active',6,6,'2026')`,[program.id]);
  const sem=await db.run(`INSERT INTO curriculum_semester(curriculumId,semesterNumber,name,minimumCredits) VALUES(?,1,'Semester 1',3)`,[curriculum.id]);
  const secondSem=await db.run(`INSERT INTO curriculum_semester(curriculumId,semesterNumber,name,minimumCredits) VALUES(?,2,'Semester 2',3)`,[curriculum.id]);
  await db.run(`INSERT INTO curriculum_course(curriculumSemesterId,courseId,required,courseType) VALUES(?,?,1,'required')`,[sem.id,course.id]);
  await db.run(`INSERT INTO curriculum_course(curriculumSemesterId,courseId,required,courseType) VALUES(?,?,1,'required')`,[secondSem.id,secondCourse.id]);
  await db.run(`INSERT INTO curriculum_course(curriculumSemesterId,courseId,required,courseType) VALUES(?,?,0,'elective')`,[sem.id,waitlistCourse.id]);
  await db.run(`INSERT INTO student_curriculum(studentId,curriculumId,status,assignedBy) VALUES(?,?,'active',?)`,[student.id,curriculum.id,admin.id]);
  for(const id of [seatHolder.id,waitlistedStudent.id])await db.run(`INSERT INTO student_curriculum(studentId,curriculumId,status,assignedBy) VALUES(?,?,'active',?)`,[id,curriculum.id,admin.id]);
  await db.run(`INSERT INTO settings(key,value) VALUES('graduationMinimumGpa','2.0')`);
  const slot=await db.run(`INSERT INTO timetable_slots(courseId,day,time,roomId,termId) VALUES(?,'Monday','09:00',?,?)`,[course.id,room.id,term.id]);
  const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
  const server=await new Promise(resolve=>{const s=app.listen(0,()=>resolve(s));});
  t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api`;
  const tokenFor=(id,role)=>jwt.sign({sub:id,role,email:`${role}@test.invalid`,mustChangePassword:false},JWT_SECRET,{expiresIn:'1h'});
  const adminToken=tokenFor(admin.id,'admin'),studentToken=tokenFor(student.id,'student');
  const seatToken=tokenFor(seatHolder.id,'student'),waitlistToken=tokenFor(waitlistedStudent.id,'student');
  async function call(method,path,token,body){const r=await fetch(base+path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();const data=text?JSON.parse(text):null;if(!r.ok)throw Object.assign(new Error(data?.error||`${r.status}`),{status:r.status,data});return data;}

  // A failed endpoint must not create a false notification.
  const beforeFailure=(await db.get('SELECT COUNT(*) n FROM notifications')).n;
  await assert.rejects(()=>call('POST','/exams',adminToken,{courseId:999999,date:tomorrow,time:'10:00',roomId:room.id,type:'final'}));
  assert.equal((await db.get('SELECT COUNT(*) n FROM notifications')).n,beforeFailure);

  const enrollment=await call('POST','/enrollments',studentToken,{courseId:course.id});assert.equal(enrollment.status,'enrolled');
  await call('GET',`/progression/${student.id}/history`,studentToken);
  await call('POST','/attendance/bulk',adminToken,{slotId:slot.id,date:'2026-02-02',entries:[{studentId:student.id,status:'absent'}]});
  await call('POST','/attendance/bulk',adminToken,{slotId:slot.id,date:'2026-02-02',entries:[{studentId:student.id,status:'absent'}]});
  const exam=await call('POST','/exams',adminToken,{courseId:course.id,date:tomorrow,time:'10:00',durationMinutes:120,roomId:room.id,termId:term.id,type:'final'});assert.ok(exam.id);
  async function addPerfectGrades(courseId){for(const [name,category,max] of [['Quiz','quiz',10],['Assignment','assignment',15],['Midterm','midterm',25],['Final','final',50]]){const item=await db.run(`INSERT INTO grade_items(courseId,name,category,maxScore) VALUES(?,?,?,?)`,[courseId,name,category,max]);await db.run(`INSERT INTO grade_scores(gradeItemId,studentId,score) VALUES(?,?,?)`,[item.id,student.id,max]);}}
  await addPerfectGrades(course.id);
  const publication=await call('POST',`/grades/courses/${course.id}/publish`,adminToken,{});assert.equal(publication.published,1);
  const appeal=await call('POST','/approvals',studentToken,{type:'appeal',payload:{courseId:course.id,reason:'Please review the final result.'}});
  await call('POST',`/approvals/${appeal.id}/decide`,adminToken,{decision:'approve',note:'Faculty review complete'});
  await call('POST',`/approvals/${appeal.id}/decide`,adminToken,{decision:'approve',note:'Registrar review complete'});
  await db.run('UPDATE terms SET isActive = 0 WHERE id = ?', [term.id]);
  await db.run('UPDATE terms SET isActive = 1 WHERE id = ?', [nextTerm.id]);
  const occupiedSeat=await call('POST','/enrollments',seatToken,{courseId:waitlistCourse.id});assert.equal(occupiedSeat.status,'enrolled');
  const waiting=await call('POST','/enrollments',waitlistToken,{courseId:waitlistCourse.id});assert.equal(waiting.status,'waitlisted');
  await call('DELETE',`/enrollments/${occupiedSeat.id}`,seatToken,{});
  assert.ok((await call('GET','/notifications',waitlistToken)).some(n=>n.type==='waitlist_promoted'&&n.entityId===waiting.id));
  const promotion=await call('POST',`/progression/${student.id}/evaluate`,adminToken,{});assert.equal(promotion.advanced,true);
  const secondEnrollment=await call('POST','/enrollments',studentToken,{courseId:secondCourse.id});assert.equal(secondEnrollment.status,'enrolled');
  await addPerfectGrades(secondCourse.id);
  await call('POST',`/grades/courses/${secondCourse.id}/publish`,adminToken,{});
  const progression=await call('POST',`/progression/${student.id}/evaluate`,adminToken,{});assert.equal(progression.graduationEligible,true);
  await call('PUT',`/finance/terms/${nextTerm.id}/config`,adminToken,{feePerCredit:100,currency:'USD'});
  await call('POST',`/finance/terms/${nextTerm.id}/generate-charges`,adminToken,{});
  await call('POST',`/finance/students/${student.id}/payments`,adminToken,{amount:300,termId:nextTerm.id,method:'cash'});
  const application=await call('POST','/graduation/applications',adminToken,{studentId:student.id,expectedGraduationTermId:nextTerm.id});
  for(let i=0;i<4;i++)await call('POST',`/approvals/${application.approvalRequest.id}/decide`,adminToken,{decision:'approve',note:`Stage ${i+1}`});
  const finalized=await call('POST',`/graduation/applications/${application.id}/finalize`,adminToken,{officialGraduationDate:'2026-06-30'});assert.ok(finalized.record.graduateNumber);

  const notifications=await call('GET','/notifications',studentToken);
  const types=new Set(notifications.map(n=>n.type));
  for(const required of ['enrollment_succeeded','attendance_posted','attendance_exam_block','exam_scheduled','grade_published','approval_submitted','approval_status_changed','progression_succeeded','graduation_eligible','invoice_generated','payment_recorded','graduation_clearance_started','graduation_clearance_decision','graduation_finalized'])assert.ok(types.has(required),`missing ${required}; received ${[...types].join(', ')}`);
  assert.ok(notifications.every(n=>n.userId===student.id));assert.ok(notifications.every(n=>n.isRead===0));assert.ok(notifications.some(n=>n.actionSection&&n.entityType&&n.entityId));
  assert.equal(notifications.filter(n=>n.type==='attendance_exam_block').length,1);
  const examNotification=notifications.find(n=>n.type==='exam_scheduled');assert.equal(examNotification.actionSection,'exams');assert.equal(examNotification.actionData.examId,exam.id);
  const before=notifications.length;await createNotification({recipientUserId:student.id,type:'graduation_finalized',message:'duplicate',deduplicationKey:`graduation-finalized:${finalized.record.id}`});
  assert.equal((await call('GET','/notifications',studentToken)).length,before);
  await call('PUT',`/notifications/${notifications[0].id}/read`,studentToken,{});const filtered=await call('GET','/notifications?status=unread&page=1&pageSize=100',studentToken);assert.equal(filtered.total,before-1);
  const staffNotifications=await db.all('SELECT * FROM notifications WHERE userId = ?',[departmentReviewer.id]);
  assert.ok(staffNotifications.some(n=>n.type==='approval_queue_entered'&&n.entityType==='approval_request'));
  const auditActions=new Set((await db.all('SELECT action FROM audit_log')).map(row=>row.action));
  for(const action of ['approval-submit','approval-decide','progress-evaluate','graduation-finalize'])assert.ok(auditActions.has(action),`missing audit action ${action}`);
  const {runNoticeScheduler}=require('../noticeScheduler');
  await runNoticeScheduler();const afterFirstReminder=(await db.get('SELECT COUNT(*) n FROM notifications')).n;
  await runNoticeScheduler();const afterSecondReminder=(await db.get('SELECT COUNT(*) n FROM notifications')).n;
  assert.equal(afterSecondReminder,afterFirstReminder);assert.ok(afterFirstReminder>(await db.get('SELECT COUNT(*) n FROM notifications WHERE type != ?',['exam_reminder'])).n);
  console.log(`isolated lifecycle notifications generated: ${before}`);
});
